
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar/navbar'
import Styles from "./layout.module.css"
import Sidebar from './components/sidebar/sidebar'
import StoreProvider from './store/StoreProvider';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  

  
  return (
    <html lang="en">
      <body className={inter.className}>

     <div className={Styles.layout}>
     <StoreProvider>
      <Sidebar />
      <div className={Styles.content}>
      <Navbar  />
      <div className={Styles.pagecontent}>
      {children}
      </div>
      </div>
      </StoreProvider>
      </div>

     
        </body>
    </html>
  )
}
